<div data-role="footer" data-id="samebar" class="nav-glyphish-example" data-position="fixed" data-tap-toggle="false">
	 <div data-role="navbar" class="nav-glyphish-example" >
		<ul>
			<li><a href="index.php" id="stream" data-icon="custom">Stream</a></li>
			<li><a href="explore.php" id="map" data-icon="custom">Explore</a></li>
			<li><a href="profile.php#history" id="coffee" data-icon="custom"><span id="username">username<span></a></li>
		</ul>
	</div> 	
</div> 